#!/bin/bash

if [ -z $1 ]
  then
    echo "
           Usage:\"pushswarm sourabh /path/to/file/to/rsync\""
else
gcloud compute instances list | grep $1 | grep -v dev | awk '{print"rsync -avz '$2'",$1":'$2' 2>&1 &"}' > /tmp/$1.sh && sh /tmp/$1.sh
gcloud compute instances list | grep $1 | grep -v dev | awk '{print"ssh -q",$1,"pkill -9 swarm && ssh -q",$1,"/root/scripts/swarm-start.sh 2>&1 &"}' > /tmp/pkill-$1.sh && sh /tmp/pkill-$1.sh
fi
