# chkconfig: 2345 20 80
# description: Start wolkdb http service

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
   /var/www/vhosts/swarm.wolk.com/src/github.com/ethereum/go-ethereum/swarmdb/server/wolkdb &
   echo $!>/var/run/wolkdb.pid
   ;;
stop)
   kill `cat /var/run/wolkdb.pid`
   rm /var/run/wolkdb.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/wolkdb.pid ]; then
      echo wolkdb is running, pid=`cat /var/run/wolkdb.pid`
   else
      echo wolkdb is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
